### ISSUE TITLE
Add config option `interval`

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/runner#30]
## Description

We want the user to be able to do some basic load testing on its endpoints.
To achieve this we can provide an `interval` options to determine the interval between two requests.
Note that this shouldn't be compatible with `concurrency != 1`, so it also require a validation update.

## Tasks

- [x] Add `RunnerOptions.Interval` (`time.Duration`) to `config.Config`
- [x] Update `configfile` CLI flags parsers accordingly
- [x] ~Update `config.Config.Validate`: it must be invalid if `interval != 0` && `concurrency != 1`~ Update: perfectly compatible with `concurrency != 1`
- [x] Implement the interval in `requester.Requester.Run`
