### ISSUE TITLE
Add config option `Request.Body`

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/runner#32]
## Description

We must be able to configure the request's body.

## Tasks

- [ ] provide the body itself
- [ ] support methods other than `GET` (`POST` and like)
- [ ] extract the body from the config and use it in `Requester.Do`
- [ ] support config file
- [ ] support flag args

We must support different encodings:
- text/plain
- application/json
- application/file (debatable for mvp, maybe later down the road)
- multipart/form-data (debatable for mvp, maybe later down the road)

## Suggestions

We do not check for compatibility between method and body (ie `GET` with non-empty body) ; it is the user responsibility (and it may vary well be intentional). This means that the `Content-Type` headers are not inferred by the body type, but user specified. Note: as this issue is separated from #31 regarding `Request.Headers`, implementation details may vary.

The yaml structure may resemble this:
```yaml
request:
  body:
    - type: "application/json" # "text/plain", ...
    - content: '{ "foo": "value", "bar": 1 }'
```

The json config file must escape embedded json body:
```json
{
  "body": {
    "type": "application/json",
    "content": "\"{\"foo\":\"value\"}\""
  }
}
```

Via cli, the input could look like:
```txt
benchttp --method POST --body-type json --body-content '{...}'
```

## Notes

Questions to answer:
- what is the best cli api (`--body-type` and `--body-content` seem strange)
- what happens with overrides concerning type and not content and vice versa
- same question but when we add `Request.Headers` config, what is the override ? At one point `Requester.Do` must set its internal request's method

**Comment by GregoryAlbouy** [comment]
@moreirathomas Some specs here do not correspond to what we decided:
- `body.type` was not intended to represent the content type, it's an information for us to know how to process `body.content`: either sending it as raw text, or a path to a file we should retrieve first (not in scope here)
- content type is a header, so it has to be set in `request.header`
- we don't want to be smart about the body and leave full control to the user to build the request they want.

That way we allow more flexibility to the user and a much less complexity in our code.

As for the CLI, I suggest a single flag `body` used similarly to header:
```sh
benchttp -body 'type:content'
```

**Comment by moreirathomas** [comment]
So let's reframe the issue then ! 

What you propose here seems clearer (it totally wasn't in my head, especially as `config.Headers` wasn't done and there was so many unknowns still).

---
The user can either states the body they will provide is `raw`, then they must pass the raw body as json: 
- `config.body.type == "raw"`
- `config.body.content == string`

If the user states the body is a `file`, they must pass the path the the file:
- `config.body.type == "file"`
- `config.body.content == fileToString(path)`

We don't care about header `Content-Type` at all here.

No validation at all of the body's content, even its length ?

> ```
> benchttp -body 'type:content'
> ```

Seems really nice ! We can split this flag value at `":"`, switch the handling around the first part and cast the second part as a `[]byte` and pass it to `http.NewRequest`.

This would really simplify #43.
