### ISSUE TITLE
Implement output strategies

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/runner#59]
## Description

We want the user to be able to choose any combination of the following output strategies:
- summary in the CLI: for a quick benchmark with immediate access to the results
- JSON file report: so they can do whatever they want with it (read it in a CI context or upload it later via the webapp)
- send directly to benchttp API server (auth is out of scope here)

## Tasks

- [ ] Define new config field `output.out` representing the 3 output strategies and handle file and CLI parsing. It must accept any combination of the three values (they're not mutually exclusive)
- [ ] Implement the actual output functions and call them according to `config.Output.out`
  - stdout: summary with key informations only (`min`, `max`, `mean` and total durations, requests done, number of errors, and any data that seems relevant but not too costly)
  - JSON file: full report output
  - benchttp API server: gob-encoded full report
- [ ] Delete function `requester.SendReport`

## Notes

- Closes #6
