### ISSUE TITLE
Implement silent mode

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/runner#61]
## Description

With #59, the runner can be integrated in a CI by reading the summary in stdout.
It's an interesting use case, but not ideal for 2 reason:
1. some convenience prints add noise to the output
2. extracting a specific information form the default summary can be tedious, and it might not even contain the desired information

Here we want to address **point 1** by allowing users to shut down all convenience prints (runner status, output labels, summary).

## Tasks

- [ ] Define new config field `output.silent` and update CLI and file parsers accordingly as well as unit tests. Expected value is a `bool`
- [ ] Update `requester` so it does not write to `stdout` if `silent == true`
- [ ] Update `output` so it does not write to `stdout` if `silent == true`
- [ ] Determine if there should be an exception for the printed default summary and the printed JSON file path

## Notes

- Blocked by #59
