### ISSUE TITLE
Implement subcommand `benchttp upload`

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/runner#81]
## Description

🚧  WIP

```sh
benchttp upload path/to/benchttp.report.20220304090000.json
```

## Tasks

- [ ] Create `cmdUpload` in `/cmd`
- [ ] Decode json file as `output.Report`
- [ ] ⚠️ TODO: determine additional validations to perform
- [ ] Send it to server via `export.HTTP`

## Notes

- Not critical if we consider the possibility to upload a report via the webapp.
