### ISSUE TITLE
Expose basic stats to option `template`

### ISSUE THREAD

**Issue by GregoryAlbouy** [benchttp/runner#83]
## Description

See #82 for context.

Once a benchmark done, we display a default summary featuring some basic stats (`min`, `max`, `mean` durations).
This summary can be overridden by a custom template with access to all `output.Report` data.
However it is currently not possible to access the computed basic stats from the template.
We want to address that by exposing basic stats to config option `template`.

## Tasks

- [ ] Expose basic stats (`min`, `max`, `mean` durations) to option `template`
- [ ] Make sure no computing is done if the stats are not requested
- [ ] Make sure the computing is done only once if stats are requested several times

## Notes

- Part of #82
