### ISSUE TITLE
Support all runner related features on the user local machine

### ISSUE THREAD

**Issue by moreirathomas** [benchttp/runner#94]
## Description

As the project has been re-scoped, we are moving towards a full local support for the runner and a gui desktop app.

The features that were offered by `server` and `worker` must move into `runner`.

## Tasks

Features that must be reimplemented:

- [ ] the raw report may be stored somewhere
- [ ] the raw report may be retrieved in order to be read later on
- [ ] the statistics are computed from the report and may be stored somewhere
- [ ] the statistics may be retrieved in order to be read later on

## Suggestions

Likely we will use the file system to store and retrieve the reports and stats (`./benchttp_runs/{run_hash}/report.json` and `./benchttp_runs/{run_hash}/stats.json`).

Thus we may need some form of an io adapter with specialized read/write methods.

**Comment by GregoryAlbouy** [comment]
Did we all agree on this? I remember considering it but not that we took a common decision.

Also if we go that way I'd do it via a fresh new repository – perhaps in a new organization but not necessarily – and keep this one intact: it's bound with the others as is and they form a whole. 

Different project, different goals, different issues...

**Comment by moreirathomas** [comment]
We mostly agreed on that on last June. But I agree it would be better to clarify what we're going for exactly. 

A new repo might be what we need. I suggest we discuss it orally and update the issue accordingly :)

**Comment by moreirathomas** [comment]
See benchttp/engine#1.
